### ISSUE TITLE
请问如果跟后台联动，保存数据

### ISSUE THREAD

**Issue by BEIBEI123** [chaijunit/bookeditor#2]
如题，请问如果跟后台联动保存数据，希望能出个demo

**Comment by chaijunit** [comment]
可以的，如果你懂python，也可以看我开源的[beibq](https://github.com/chaijunit/beibq)，具体代码在https://github.com/chaijunit/beibq/blob/master/app/api/views/book.py

**Comment by BEIBEI123** [comment]
好的，谢谢
